### PR TITLE
HDF5 Support

### PR DESCRIPTION
**Pull request by rennehan**
Hi Rafael,

I love this simple IC generator! I added support for HDF5 as I'm using GIZMO, and I find it easier to work in HDF5 than in Gadget2 binary format. The modifications I have made output double precision HDF5 files for now, with a GIZMO-like header (very similar to Gadget, with a couple of extra fields for information). This shouldn't matter too much, since they can be ignored when reading the HDF5 header and the byte size doesn't matter. If you have any questions let me know, and if you want to merge it into your code feel free!

-Doug Rennehan (rennehan@uvic.ca)

### CODE REVIEW

**Comment by ruggiero** [comment]
Hi Doug, thanks for the pull request! Being able to write in HDF5 is a great addition to the code. I tried testing the --hdf5 option and got the following error, does it not happen to you?

```
Traceback (most recent call last):
  File "galstep.py", line 535, in <module>
    main()
  File "galstep.py", line 33, in main
    write_input_file(galaxy_data)
  File "galstep.py", line 520, in write_input_file
    file_format=file_format)
  File "/tmp/galstep/galstep/snapwrite.py", line 204, in write_snapshot
    assert np.shape(Z[start:end]) == (n_part[i], raw_hdata[29])
AssertionError
```

**Comment by rennehan** [comment]
Hi Rafael, 

No problem! Could be if you tested it with Flag_Metals = 0 or 1. I wrote this today for my runs which use 10 metal fields, so I didn't get a chance to test the other cases. I also made a slight change to the way Flag_Metals is handled, since in GIZMO it actually tells you the total number of fields in the Metallicity array.

The line:
assert np.shape(Z[start:end]) == (n_part[i], raw_hdata[29])

Makes sure that the Z array has the same shape as (n_part[i], Flag_Metals). n_part[i] is the number of particles in that component, and Flag_Metals should tell you how many metallicity fields you have. I can see this breaking if Flag_Metals == 1 or Flag_Metals == 0 since the shape should be blank. This would mean the shape was (n_part[i], 1) which is not valid since it should be (n_part[i], ). You can remove this line and see if it works without it, or put an IF statement around it for the special case of 1 metal field.

Let me know how that goes.

**Comment by rennehan** [comment]
I fixed it and ran a test with Flag_Metals = 1 and it worked fine. The new commits reflect these changes.

**Comment by ruggiero** [comment]
Thanks for fixing it @rennehan, it indeed seems to be working just fine now :)

I have just merged the pull request, and will update the README to reflect this update.

**Pull request merged**
